---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: "Install packages"
    package:
      name:
        - python3
        - python3-pip
        - seclists 
        - curl 
        - dnsrecon 
        - enum4linux 
        - feroxbuster 
        - gobuster 
        - impacket-scripts 
        - nbtscan 
        - nikto 
        - nmap 
        - onesixtyone 
        - oscanner 
        - redis-tools 
        - smbclient 
        - smbmap 
        - snmp 
        - sslscan 
        - sipvicious 
        - tnscmd10g 
        - whatweb 
        - wkhtmltopdf
        - python3-venv

  - name: "Install Autorecon"
    ansible.builtin.pip:
      name: git+https://github.com/Tib3rius/AutoRecon.git
        
  - name: "Install Threader3000"
    ansible.builtin.pip:
      name: threader3000

  - name: "Fix PATH in zshrc"
    copy: 
      src: "{{ playbook_dir }}/files/zshrc"
      dest: "/home/kali/.zshrc"
